- hosts: all
  become: true
  tasks:
    - name: Base packages
      apt:
        update_cache: true
        name: [curl]
        state: present

- hosts: masters
  become: true
  tasks:
    - name: Install k3s server
      shell: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --cluster-init --write-kubeconfig-mode 644" sh -
      args: { creates: /usr/local/bin/k3s }

    - name: Read node token
      slurp:
        src: /var/lib/rancher/k3s/server/node-token
      register: token_b64

    - name: Set token fact
      set_fact:
        k3s_token: "{{ token_b64.content | b64decode | trim }}"

- hosts: workers
  become: true
  vars:
    master_ip: "{{ hostvars['spark-master']['ansible_host'] }}"
    token: "{{ hostvars['spark-master']['k3s_token'] }}"
  tasks:
    - name: Install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ master_ip }}:6443 K3S_TOKEN={{ token }} sh -
      args: { creates: /usr/local/bin/k3s-agent }
